### ISSUE TITLE
horizontal elevator kill is janky

### ISSUE THREAD

**Issue by dataGuyJosh** [thommoboy/There-are-no-brakes#157]
player ends up in weird positions when they hit the kill trigger on the elevator

Possible solution:
Place a trigger on the left wall where the player would be crushed, if player and elevator are in that collider at the same time THEN teleport to position where they dropped (left of the elevator), don't bother with the right side as they get pushed into the hole to one of the pressure plates which is actually useful

**Comment by NAT0P0TAT0** [comment]
well how it works is theres a respawn point inside where the platform will be and a kill trigger inside the left wall, so players will only hit it if theyre being squished and their collider starts going through the wall

also the right side shouldnt respawn them unless they actually jump right at the end, otherwise theyd just fall into the path on the right

if the positioning is weird we can just move the respawn trigger position
