### ISSUE TITLE
Ancients Doors

### ISSUE THREAD

**Issue by dataGuyJosh** [thommoboy/There-are-no-brakes#31]
door allows multiple people to pass through it if they are both in front of the door (allowing people to car-pool with an ancient player to get past a door in the tutorial level)

**Comment by NAT0P0TAT0** [comment]
i thought this couldnt be possible since the door script only checks for player 2, but noticed you can pick up another player and use the door with the same button press and since picking up someone else makes them a child object they get moved too.

ill just make the doors activate the 'drop' function before doing anything and it should be fine.
