### ISSUE TITLE
Cannon Ball bug

### ISSUE THREAD

**Issue by dataGuyJosh** [thommoboy/There-are-no-brakes#57]
when the player uses the interact button on the cannon ball, it is picked up BUT (because it is attached to joints) the player is flung many miles across into the atmosphere!

_There's a starman waiting in the sky
He'd like to come and meet us
But he thinks he'd blow our minds_

David Bowie - Starman Lyrics

**Comment by NAT0P0TAT0** [comment]
yeah the cannonball just needs to not be tagged 'weight', that tag is used by player pickup and pulleys
since the pushable cannon ball isnt supposed to be picked up and isnt thrown into a pulley it should lose the weight tag

though i think the wall break script checks for it so that should be changed to check for the new tag
